### ISSUE TITLE
Improving documentation for function `I18n.add(items, locale, prefix)`

### ISSUE THREAD

**Issue by mesr** [ficusjs/ficusjs-docs#36]
Hello there! And thank you for putting together and maintaining this awesome framework.

I am reading through the documentation, specifically the section about Internationalization, and I noticed a few places where the information given seems insufficient, specifically in [page *createI18n*, section *Methods* / *add(items, locale, prefix)*](https://docs.ficusjs.org/i18n/create-i18n/#add-items-locale-prefix):

- The possibility of passing an array of strings for pluralization purpose as value to messages is not explicitly stated and must be interpreted from reading the section about function `setPluralizationRule(locale, rule, options)`, and confirmed by looking at the source code. Maybe something along the lines of the following would constitute a more descriptive wording:
  > items	...	The object containing messages. The value of each message can be a simple string or, in the case of pluralized messages, an array of strings.

- It seems unclear to me without looking at the source code what the *prefix* parameter is for and how it is handled by that function. I feel that a slightly more descriptive wording could improve understanding, such as:
  > prefix	...	An optional prefix for messages. It will be automatically prepended to each item's key.

Please let me know what are you guys' thoughts on that.

**Comment by ducksoupdev** [comment]
Hi @mesr, thanks for your recommendations. We are always looking for ways to improve the docs. These are all good suggestions and would improve the clarity of the docs. Are you happy to submit a PR with suggestions?

**Comment by mesr** [comment]
Hello @ducksoupdev, I am happy to do so. This will be my first time contributing to a project on Github. Please allow me some time to review the documentation that explains how this is done. I have other, more involving, features that I wish to discuss and possibly contribute to the I18n module. This first PR is be a good way to get started at it. Thanks!

**Comment by mesr** [comment]
Thanks @ducksoupdev! More coming up.
